[workspace]
members = ["rivet-orchestrator", "rivet-runner", "rivet-core", "rivet-cli"]
resolver = "3"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
